const myName = 'Matvey';
const mySurname = 'Borisov';
let myFavoriteDrink = 'Pineapple juice';
let myFavoriteAnimal = 'Dog';
let myFavoriteProgrammingLanguage = 'JavaScript';
console.log(myName);
console.log(mySurname);
console.log(myFavoriteDrink);
console.log(myFavoriteAnimal);
console.log(myFavoriteProgrammingLanguage);